apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.envSecret }}
  {{ $key }}: {{ $val }}
  {{- end }}
